-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgOuUROdwtwJNYeY42
Z28Hd4uwMqMRW37RvGa3awYxaM+gCgYIKoZIzj0DAQehRANCAAShkgr7fU9XRWLP
PWUerHuupvSIqeVZX6IjUohsUxc/y1UMfLhCs3hU2cizN1g8+RCg5eauxzToO7JX
pQEkQQnj
-----END PRIVATE KEY-----