name: aboutbelgium
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style genders.
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7
  http: any
  youtube_player_flutter: any
  url_launcher: ^6.3.1
  firebase_core: ^3.6.0
  firebase_analytics: ^11.3.3
  firebase_auth: ^5.3.1
  firebase_messaging: ^15.1.3
  firebase_storage: ^12.3.3
  firebase_in_app_messaging: ^0.8.0+8
  firebase_database: ^11.1.4
  firebase_admin: ^0.3.0
  cloud_firestore: ^5.4.4
  cloud_functions: ^5.1.3
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  image: ^4.2.0
  sizer: ^3.0.4
  path_provider: ^2.1.4
  google_fonts: ^6.2.1
  sign_in_button: ^3.2.0
  permission_handler: ^11.3.1
  firebase_app_check: ^0.3.1+4
  google_mobile_ads: ^5.2.0
  shared_preferences: ^2.3.2
  font_awesome_flutter: ^10.8.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.2
  advertising_id: ^2.7.1
  change_app_package_name: ^1.4.0
  sign_in_with_apple: ^6.1.3

fonts:
  - family: Roboto
    fonts:
      - asset: fonts/Roboto-Regular.ttf
      - asset: fonts/Roboto-Bold.ttf
dev_dependencies:
  flutter_test:
    sdk: flutter


  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:



  uses-material-design: true
  assets:
    - assets/languages/
    - assets/flags/
    - assets/images/
    - assets/backgrounds/
    - assets/genders/
    - assets/images/splash.png
    - assets/images/aboutBelgiumLogo.png


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/aboutBelgiumLogo.png"
  adaptive_icon_background: "#ffffff" # veya farklı bir renk kodu
  adaptive_icon_foreground: "assets/images/aboutBelgiumLogo.png"


flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.png
  android : true
  ios : true
  android_12:
    image: assets/images/splash.png
    android : true



