// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbTWWNb5PUwzrxg27q2Ao1AKYXcbXaY4c',
    appId: '1:1041726977158:android:eab548b442d97053404d07',
    messagingSenderId: '1041726977158',
    projectId: 'aboutbelg',
    databaseURL: 'https://aboutbelg-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'aboutbelg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1a7gMYpWC7qbozwqxQPqkVsNmgQOjVQM',
    appId: '1:1041726977158:ios:bb84a365b29b13b2404d07',
    messagingSenderId: '1041726977158',
    projectId: 'aboutbelg',
    databaseURL: 'https://aboutbelg-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'aboutbelg.appspot.com',
    androidClientId: '1041726977158-g85lmgmuvsc2p7tpmi9o26l477fhsrbj.apps.googleusercontent.com',
    iosClientId: '1041726977158-m16sjkibktl9o5m9lcvhskqral0lu0sa.apps.googleusercontent.com',
    iosBundleId: 'com.ysrtrk.aboutbelgium',
  );

}